method: bayes  # or 'grid', 'bayes'
metric:
  name: val_accuracy
  goal: maximize

parameters:
  num_filters:
    values: [32, 48, 64]
    
  activation_function:
    values: [ReLU, GELU, SiLU, Mish, leaky_relu]
    
  filter_growth:
    values: [0.5, 0.7, 0.9, 1, 1.2]
    
  data_augmentation:
    values: [True, False]
    
  batch_norm:
    values: [True, False]
  
  kernel_size:
    values: [3, 5]
    
  dropout:
    values: [0.25, 0.5]
